### ISSUE TITLE
分割算法代码问题

### ISSUE THREAD

**Issue by sighdn** [yulisun/SCEM#1]
您好，我正在使用您的算法作为我在做的工作的对比算法，我注意到您提供的代码生成了一张差异图，但是没有直接生成CM图，方便的话可以请您提供相关部分的代码吗，谢谢

**Comment by yulisun** [comment]
同学你好，生成CM使用的是基于MRF的分割方法，我在SCASC和IRG-McS里面都已经上传了，你可以下载参考。如有疑问，可以直接邮件联系，sunyuli@mail.ustc.edu.cn
